### ISSUE TITLE
Create the stock inventory page

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-reporting#51]
- [ ] Title of the page 'Stock Usage Report'
- [ ] The month and year is a drop down selection (#52)
- [ ] There will be NO button for Stock Usage Report
- [ ] Each row will consist of a different item. Items included and order they should appear: ORS 5, Zinc 10, Paracetamol, COC, POP, Male Condoms, Female Condoms, Cycle beads (Standard day method), Emergency Contraceptive, RDTs, AL 6, AL 12, AL 18, AL 24
- [ ] Text in each row on the left will be: (first line of text) Item name, (second line of text) Unit of measure. Please see the table below for the units by item

Item | Unit of Measure 
 --- | ---
ORS 5 | Packets |
Zinc 10 | Tablets |
Paracetamol | Tablets |
COC | Packs |
POP | Packs |
Male Condoms | Pieces |
Female Condoms | Pieces |
Cycle beads (Standard day method) | Pieces |
Emergency Contraceptive | Packs |
RDTs | Tests | 
AL 6 | Tablets |
AL 12 | Tablets |
AL 18 | Tablets |
AL 24 | Tablets |

- [ ] Text in each row on the right will be count of each item used in the current selected month (#53 )
- [ ] Clicking an item will take you another page providing the item usage for the previous months (#54 )

Please see the image below for more information on what this page is meant to look like
![page](https://user-images.githubusercontent.com/20777928/74755561-6a409700-5284-11ea-9882-5457844d85ba.png)

**Comment by msschroeder** [comment]
lgtm
