### ISSUE TITLE
Create the Service Activity Reporting page

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-reporting#64]
- [ ] Title: "Service activity reporting"
- [ ] Clicking on the Daily Tallies tab, takes you to the Daily Tallies tab ( #70  )
- [ ] Clicking on the Draft Monthly tab, takes you to the Draft Monthly tab ( #65 )
- [ ] Clicking on the Sent Monthly tab,  takes you to the Sent Monthly tab (#73  )
- [ ] Clicking the hamburger menu on the upper left corner, opens the side panel
- [ ] Swiping to the left, opens the side panel

![image1](https://user-images.githubusercontent.com/20777928/75347042-f9ffca00-58b0-11ea-964b-59f85235d148.png)

**Comment by msschroeder** [comment]
lgtm
