### ISSUE TITLE
Generate the draft report - CHW

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-reporting#68]
- [ ] Once you have selected the month of the report (#66 ) or you have selected the draft report previously saved, you will be taken to the draft report (shown below in figure 1)
- [ ] New draft reports shows all the values calculated when I generated the report.
- [ ] Previously saved draft shows all the values calculated when I generated it and those I saved.
- [ ] Report is generated based on the daily tallies
- [ ] Counts/tallies are calculated based on what is outlined in this section (#69)
- [ ] If there are no counts/tallies generated from the app, a default of 0 is assigned
- [ ] All fields are writable
- [ ] There is pagation (#74 )
- [ ] When I click SAVE, it save any updates I have made to the report
- [ ] When I click CONFIRM at the bottom, it will generate a message (#67  )

![image10](https://user-images.githubusercontent.com/20777928/75349921-a6907a80-58b6-11ea-95c4-fa619207b7fb.png)

**Comment by msschroeder** [comment]
lgtm

**Comment by msschroeder** [comment]
lgtm
